- profiles/local-frontend-and-api.js
- src/api/apiClient.tsx
Change our api prefix:
before:
`/api/migration-analytics`
after
`/api/xavier`
> WINDUP-2396 (MA) Deploy to Insights Test Environment - Change api prefix

- src/PresentationalComponents/Reports/Environment/Environment.test.tsx
- src/PresentationalComponents/Reports/Environment/Environment.tsx
- src/PresentationalComponents/Reports/Environment/__snapshots__/Environment.test.tsx.snap
This change should allow the backend to send percentage values in the format:  **value > 0 && value < 1**. Then the UI will multiply the value by 100 and show it to the user.
As a result:
> MIGENG-27 UX Implementation - Initial Savings Estimation Report - Fix percentage conversion

- src/api/apiClient.tsx
- src/api/apiInit.tsx
- src/entry-dev.tsx
- src/entry.tsx
https://jira.coreos.com/browse/MIGENG-113
added Axios interceptor to call `getUser()` in every request.
- Calling `getUser` in every request will **refresh the token once it is expired**.
- `getUser` method is managed by chrome.js which is generated by `insights-chrome` project.
> MIGENG-113 Migration Analytics Web UI - Need to refresh authentication token

- src/PresentationalComponents/FancyGroupedBarChart/FancyGroupedBarChart.tsx
- src/PresentationalComponents/FancyGroupedBarChart/__snapshots__/FancyGroupedBarChart.test.tsx.snap
Problem:
If the user puts the mouse over a bar, then the Tooltip is partially hidden
This PR solves that problem. The problem was caused by a custom color for the tooltip I was using. Now I removed it and using the default configuration
https://jira.coreos.com/browse/MIGENG-142
> MIGENG-191 UX Initial Savings Estimation - Barchart tooltip not readable

- src/pages/ReportView/WorkloadSummary/WorkloadSummary.tsx
Changed the Workload Summary Report / Target recommendation:
- Change from "Workloads running, or possible to migrate to Red Hat Enterprise Linux" to "Workloads possible to migrate to RHEL"
BEFORE:
AFTER:
> Change WSR - Target recommendation label

- src/pages/ReportView/WorkloadSummary/WorkloadSummary.tsx
Changed the Workload Migration Summary Report - Workloads detected (OS Types)
- Added a second line in the Donut chart tooltip to present to the user complete information about the percentage's original values
BEFORE:
AFTER:
> WMS - Workloads detected (OS Types): add workloads to tooltip

- src/PresentationalComponents/FancyGroupedBarChart/FancyGroupedBarChart.scss
- src/PresentationalComponents/FancyGroupedBarChart/FancyGroupedBarChart.tsx
- src/PresentationalComponents/FancyGroupedBarChart/__snapshots__/FancyGroupedBarChart.test.tsx.snap
- src/pages/ReportView/InitialSavingsEstimation/InitialSavingsEstimation.tsx
Reduce left padding of:
- Cost expenditure comparison during the 3 year migration
- Project cost breakdown
I can not reduce the padding to 0 but I've reduced the padding in a way that values less or equal than 99,000,000 can still be visible in the chart.
Before:
After:
> Initial Savings Estimation - reduce left padding of barcharts

- src/pages/ReportView/WorkloadSummary/WorkloadSummary.tsx
https://jira.coreos.com/browse/MIGENG-189
Uncommented the `Scans run` box in the Workload Summary Report.
It nad been commented in https://github.com/project-xavier/xavier-ui/pull/45/commits/64b978ae27a7e7ff2a06676c73e147c07842d0de
This has been tested during the reviews of https://github.com/project-xavier/xavier-integration/pull/53 and https://github.com/project-xavier/xavier-analytics/pull/25
> MIGENG-189 Uncommented 'Scans run' box in WSR

- src/SmartComponents/Reports/FlagsTable/FlagsTable.tsx
- src/SmartComponents/Reports/WorkloadsDetectedTable/WorkloadsDetectedTable.tsx
When No-Results tables are shown, there is a border which is unnecessary; it is caused by double CARD component used.
Affected tables: 
- Workloads detected
- Flags (Considerations to be migrated)
BEFORE:
AFTER
> Workload Migration Summary: Remove borders from No-results table

- src/pages/ReportView/WorkloadSummary/WorkloadSummary.tsx
Changed the Skeleton layout of Workload Migration Summary Report to better represent the report layout.
The screenshot below is the final view of the report:
**BEFORE CHANGES:**
**AFTER CHANGES (this is a better skeleton for the final report view)**
> Workload Migration Summary: change Skeleton layout

- src/pages/ReportsUpload/ReportsUpload.tsx
- src/pages/ReportsUpload/UploadForm.tsx
- src/pages/ReportsUpload/__snapshots__/ReportsUpload.test.tsx.snap
- src/pages/ReportsUpload/__snapshots__/UploadForm.test.tsx.snap
Changes in the Upload Form:
- Removed `accept` validation. Now the user will be able to select any file with any extension. This change is due to every Operating System have different Mime-type and the current UI is not working on Mac or Windows OS.
- Added maxSize validation. **Current MaxSize is 1073741824Kb (1GB)**
> MIGENG-129: MA - MIME Type Validation

- package.json
- src/PresentationalComponents/ReportViewPage/__snapshots__/ReportViewPage.test.tsx.snap
- src/PresentationalComponents/Reports/ScansRunTable/ScansRunTable.tsx
- src/Utilities/formatValue.js
https://jira.coreos.com/browse/MIGENG-194
Changes:
- Change date to EN format.
**Before:**
15 May 2019
**After:**
May 15, 2019
- Added time (just hour and minute) to dates.
e.g. September 19, 2019 5:38 PM
The current version is using EN format for numbers and I think we should use EN formatting for dates as well. When we will add internationalization we can change the date format.
> MIGENG-194: MA - Analysis List - include timestamp in dates

- package.json
- src/PresentationalComponents/Reports/Environment/Environment.tsx
- src/PresentationalComponents/Reports/Environment/__snapshots__/Environment.test.tsx.snap
https://issues.redhat.com/browse/MIGENG-269
Changes in the initial saving estimation report:
- "ESXi hypervisors (2-socket servers)" to "Licenses for ESXi Hypervisors (2 socket)"
- "ESXi hypervisors would be migrated to RH technologies" for "VMware licenses (2 socket) to migrated to RH technologies"
> MIGENG-269: Different "ESXi hypervisors (2-socket servers)" count in CF MA UI vs. MA SaaS report

- src/Utilities/extractUtils.test.tsx
- src/Utilities/extractUtils.tsx
- src/pages/ReportsUpload/UploadForm.tsx
https://issues.redhat.com/browse/MIGENG-173
Remove all the extensions of a file and show it in the `Report Name` field of the Upload Form page. E.g.
- Filename = "myFile.json", then `Report Name`=myFile
- Filename = "myFile.tar.gz", then `Report Name`=myFile
- Filename = "myFile.whatever.tar.gz", then `Report Name`=myFile
> MIGENG-173: UI Upload Form: Default “Report Name” should not include the extension of the file

- src/actions/ReportActions.tsx
- src/api/report.tsx
- src/models/state/index.tsx
- src/pages/ReportView/WorkloadInventory/WorkloadInventory.tsx
- src/pages/ReportView/WorkloadInventory/index.tsx
- src/reducers/ReportsReducer.test.tsx
- src/reducers/ReportsReducer.tsx
https://jira.coreos.com/browse/MIGENG-279
Changed the "Workload migration inventory" page and added a Kebab dropdown button with options:
- Download all as CSV (Download a CSV of all data related to this report)
- Download as CSV (Download a CSV using the filters applied on the page)
> MIGENG-279: 'Export as CSV' does not export filtered result

- src/SmartComponents/Reports/FlagsTable/FlagsTable.tsx
- src/pages/ReportView/WorkloadInventory/WorkloadInventory.tsx
https://issues.redhat.com/browse/MIGENG-407
- Removed static width of the table **Flags (Considerations to be migrated)**
Before:
After:
- Removed static width of the table "Workload migration inventory"
Before:
After:
> MIGENG-407: MA - Rule: Hotplug for CPU / Memory

- src/pages/ReportView/WorkloadInventory/WorkloadInventory.tsx
- src/pages/ReportView/WorkloadInventory/index.tsx
https://issues.redhat.com/browse/MIGENG-523
Replace the current 2 options for downloading a CSV file for a single Button. The behavior of the "Export to CSV" button:
- If no filter was selected then it will download all the elements of the table regardless of the current page where the user is located.
- If any filter was selected then it will download just the elements that match the filter criteria.
- If any of the columns where sorted then the exported CSV will use the same sorting criteria, otherwise it will use the default sort order.
**Current version in CI:**
**Screenshot of the PR:**
> MIGENG-523: MA [RFE] Export CSV options are not clear enough

- src/pages/ReportView/WorkloadInventory/WorkloadInventory.tsx
https://issues.redhat.com/browse/MIGENG-589
Added tooltip to `workload` and `Efford` column in the Workload Inventory Report Table
> MIGENG-589: UI implementation - WIR Flags and Targets

- src/PresentationalComponents/Reports/ScansRunTable/ScansRunTable.test.tsx
- src/PresentationalComponents/Reports/ScansRunTable/__snapshots__/ScansRunTable.test.tsx.snap
- src/models/Report.tsx
- src/pages/Reports/Reports.test.tsx
- src/pages/Reports/__snapshots__/Reports.test.tsx.snap
https://issues.redhat.com/browse/MIGENG-623
UI changes needed to support the change on the backend that will export JSON dates using ISO-8601 format instead of a timestamp.
Elements covered :
* Return correct Error Codes ----> IMPLEMENTED
* Pagination parameters : limit,offset ----> NOT APPLICABLE
* Pagination maximum value for limit ----> NOT APPLICABLE
* Pagination response object : meta,links,data ----> NOT APPLICABLE
* Links object containing First and Last ----> NOT APPLICABLE
* Filtering results returned in the data element ----> NOT APPLICABLE
* Sorting response inside data element ----> NOT APPLICABLE
* Date data type folling ISO-8601 format ----> IMPLEMENTED
* Objects canonical ID ----> ON HOLD
* Oerations MUST have an operationId defined ----> IMPLEMENTED
Depends on : …
> MIGENG-623 modifying date fields adding string type

- src/PresentationalComponents/WorkladSummary/ApplicationPlatformsCard/ApplicationPlatformsCard.tsx
- src/PresentationalComponents/WorkladSummary/JavaRuntimesCard/JavaRuntimesCard.tsx
- src/PresentationalComponents/WorkladSummary/OSInformation/OSInformation.tsx
- src/pages/ReportView/InitialSavingsEstimation/InitialSavingsEstimation.tsx
https://issues.redhat.com/browse/MIGENG-674
- Initial Savings estimation
- `Total costs during 3 years migration`: Increased `width` of legends
- `Cost expenditure comparison during the 3 year migration` and `Project cost breakdown` Reduce padding to 30 so `Y` axis is shown correctly
Steps to reproduce the error and then compare it with the current PR: https://issues.redhat.com/browse/MIGENG-674?focusedCommentId=14203203&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14203203
> MIGENG-674: Element is not displayed properly

- src/PresentationalComponents/FancyChartDonut/FancyChartDonut.tsx
- src/PresentationalComponents/FancyChartDonut/__snapshots__/FancyChartDonut.test.tsx.snap
- src/PresentationalComponents/WorkladSummary/ApplicationPlatformsCard/ApplicationPlatformsCard.tsx
- src/PresentationalComponents/WorkladSummary/ApplicationPlatformsCard/__snapshots__/ApplicationPlatformsCard.test.tsx.snap
- src/PresentationalComponents/WorkladSummary/JavaRuntimesCard/JavaRuntimesCard.tsx
- src/PresentationalComponents/WorkladSummary/JavaRuntimesCard/__snapshots__/JavaRuntimesCard.test.tsx.snap
- src/PresentationalComponents/WorkladSummary/OSInformation/OSInformation.tsx
- src/PresentationalComponents/WorkladSummary/OSInformation/__snapshots__/OSInformation.test.tsx.snap
- src/pages/ReportView/InitialSavingsEstimation/InitialSavingsEstimation.tsx
- src/pages/ReportView/WorkloadSummary/WorkloadSummary.tsx
- src/pages/ReportView/WorkloadSummary/__snapshots__/WorkloadSummary.test.tsx.snap
https://issues.redhat.com/browse/MIGENG-654
Fixes to comment: https://issues.redhat.com/browse/MIGENG-654?focusedCommentId=15157206&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-15157206
- Use of **Red Hat OpenShift Virtualization** with **V** capitalized:
- Added "See the Workload migration inventory for details" tooltip to the 3 Cards "Operating system information", "Oracle Java runtime information", and "Application server platform information". All those 3 cards have the same tooltip message
- Changed "VMWare" to "VMware":
> MIGENG-654: UI changes for Workload Migration Summary UI - Fixes
