project-xavier/xavier-ui

src/pages/ErrorPage/ErrorPage.tsx, src/pages/ErrorPage/__snapshots__/ErrorPage.test.tsx.snap
With this change, the user will be able to click on the "Home" button and retry to load the page.
=> Error page - Fix Home button

src/pages/ReportView/InitialSavingsEstimation/InitialSavingsEstimation.tsx
This should change the source and target of the Initial Savings estimation report.
=> MIGENG-27 UX Implementation - Initial Savings Estimation Report - change source and target values

src/PresentationalComponents/ReportViewPage/ReportViewPage.test.tsx, src/PresentationalComponents/ReportViewPage/ReportViewPage.tsx, src/PresentationalComponents/ReportViewPage/__snapshots__/ReportViewPage.test.tsx.snap, src/models/Report.tsx, src/pages/ReportView/InitialSavingsEstimation/InitialSavingsEstimation.tsx, src/pages/ReportView/ReportView.test.tsx, src/pages/ReportView/__snapshots__/ReportView.test.tsx.snap, src/pages/Reports/Reports.test.tsx, src/pages/Reports/Reports.tsx, src/pages/Reports/__snapshots__/Reports.test.tsx.snap, src/reducers/ReportsReducer.test.tsx, src/reducers/__fixtures__/reports.tsx
Changed the structure of Report Model.
Now we are able to use ReportName and ReportDescription across all the UI.
This PR affects the REPORT LIST page and the VIEW EDIT page
=> MIGENG-145: Reports List (Analysis Executions) - Name field

src/pages/ReportsUpload/ReportsUpload.tsx, src/pages/ReportsUpload/__snapshots__/ReportsUpload.test.tsx.snap
Form upload form: The year by year percentages changed to 50,30,20 respectively.
https://jira.coreos.com/browse/MIGENG-167
=> MIGENG-167 MA - ICS Parameter Maintenance

src/pages/ReportsUpload/UploadForm.tsx
Upload Form: Default “Report Name” will not include the extension of the file anymore
https://jira.coreos.com/browse/MIGENG-173
=> MIGENG-173 UI Upload Form: Default “Report Name” should not include the extension of the file

profiles/local-frontend-and-api.js, src/PresentationalComponents/ReportViewPage/ReportViewPage.tsx, src/PresentationalComponents/ReportViewPage/__snapshots__/ReportViewPage.test.tsx.snap, src/pages/ReportView/ReportView.js, src/pages/ReportView/ReportView.test.tsx, src/pages/ReportView/__snapshots__/ReportView.test.tsx.snap
https://jira.coreos.com/browse/MIGENG-172
Changed the order of tabs. Now the new order will be:
From left to right
- Initial savings estimation
- Workload migration summary
- Workload migration inventory
=> MIGENG-172 View Analysis UI: Change the order of tabs

src/PresentationalComponents/Reports/ProjectCostBreakdownTable/ProjectCostBreakdownTable.test.tsx, src/PresentationalComponents/Reports/ProjectCostBreakdownTable/ProjectCostBreakdownTable.tsx, src/pages/ReportView/InitialSavingsEstimation/InitialSavingsEstimation.tsx
Changed the formula used by the "Project cost breakdown" table:
**Before:**
year1RhvGrandTotalGrowthValue + year2RhvGrandTotalGrowthValue + year3RhvGrandTotalGrowthValue
**After:**
year1RhvTotalGrowthValue + year2RhvTotalGrowthValue + year3RhvTotalGrowthValue
https://jira.coreos.com/browse/MIGENG-169
=> MIGENG-169: MA - Cost Savings Report - Growth Subscriptions

src/pages/ReportView/InitialSavingsEstimation/InitialSavingsEstimation.tsx
Total VMware maintenance, Red Hat Virtualization… remove “)”
https://jira.coreos.com/browse/MIGENG-168
=> MIGENG-168: MA - Cost Savings Report - narrative

src/pages/ReportView/InitialSavingsEstimation/InitialSavingsEstimation.tsx
This PR removes the disclaimer until we have a clear idea about the context of it
=> Initial Savings Estimation - Remove the disclaimer

src/pages/ReportView/WorkloadInventory/WorkloadInventory.tsx
- Fix chip labels.
- Reset input text after pressing ENTER or "Clear filters"
=> Fix workload inventory filtering: Chips and input text

src/pages/GettingStarted/GettingStarted.tsx, src/pages/GettingStarted/__snapshots__/GettingStarted.test.tsx.snap
https://jira.coreos.com/browse/MIGENG-266
New layout
=> MIGENG-266 Changed first page text layout

src/pages/ReportView/InitialSavingsEstimation/InitialSavingsEstimation.tsx
Added suggested disclaimer to Initial savings estimation report.
=> MIGENG-147: Initial Costs Saving Report - Disclaimer

src/PresentationalComponents/ReportViewPage/__snapshots__/ReportViewPage.test.tsx.snap, src/Utilities/formatValue.js
=> MIGENG-194: MA - Analysis List - include timestamp in dates

src/PresentationalComponents/Reports/SummaryTable/SummaryTable.tsx
https://jira.coreos.com/browse/MIGENG-283
=> MIGENG-283: WSR - Summary Table - Column header Host -> Hosts

src/PresentationalComponents/Reports/ScansRunTable/ScansRunTable.test.tsx, src/PresentationalComponents/Reports/ScansRunTable/ScansRunTable.tsx, src/PresentationalComponents/Reports/ScansRunTable/__snapshots__/ScansRunTable.test.tsx.snap, src/models/Report.tsx
https://issues.redhat.com/browse/MIGENG-370
=> MIGENG-370: MA - Change Type value's logic in WSR

profiles/local-frontend-and-api.js, src/PresentationalComponents/ReportViewPage/ReportViewPage.tsx, src/PresentationalComponents/ReportViewPage/__snapshots__/ReportViewPage.test.tsx.snap, src/models/Report.tsx, src/pages/ReportView/WorkloadSummary/WorkloadSummary.tsx
https://issues.redhat.com/browse/MIGENG-331
Changes:
- "Unknown" is misspelled as "Unknow"
-  Added the unsupported complexity
=> MIGENG-331: Typo in MA, Workload Migration Summary AND add unsupported complexity

profiles/local-frontend-and-api.js, src/pages/ReportView/WorkloadInventory/WorkloadInventory.tsx, src/pages/ReportView/WorkloadInventory/WorkloadInventoryDetails/WorkloadInventoryDetails.test.tsx, src/pages/ReportView/WorkloadInventory/WorkloadInventoryDetails/WorkloadInventoryDetails.tsx, src/pages/ReportView/WorkloadInventory/WorkloadInventoryDetails/__snapshots__/WorkloadInventoryDetails.test.tsx.snap, src/pages/ReportView/WorkloadInventory/WorkloadInventoryDetails/index.tsx
https://issues.redhat.com/browse/MIGENG-500
=> MIGENG-500: MA UI/UX: Update units GB to GiB

src/App.scss, src/PresentationalComponents/SolidCard/SolidCard.test.tsx, src/PresentationalComponents/SolidCard/SolidCard.tsx, src/PresentationalComponents/SolidCard/__snapshots__/SolidCard.test.tsx.snap, src/PresentationalComponents/SolidCard/index.tsx, src/models/Report.tsx, src/pages/ReportView/WorkloadSummary/WorkloadSummary.tsx
https://issues.redhat.com/browse/MIGENG-438
- Depends on https://github.com/project-xavier/xavier-integration/pull/94
- Added CNV to the panel of recommended targets
- Keep RHEL recommended target until `OS Information and Recommendation` panel is ready
=> MIGENG-438: CNV Target - WSR report implementation

src/models/Report.tsx, src/pages/ReportView/WorkloadInventory/WorkloadInventoryDetails/WorkloadInventoryDetails.test.tsx, src/pages/ReportView/WorkloadInventory/WorkloadInventoryDetails/WorkloadInventoryDetails.tsx, src/pages/ReportView/WorkloadInventory/WorkloadInventoryDetails/__snapshots__/WorkloadInventoryDetails.test.tsx.snap
https://issues.redhat.com/browse/MIGENG-507
Dependencies:
- https://github.com/project-xavier/xavier-integration/pull/99
- https://github.com/project-xavier/xavier-analytics/pull/56
Added the Insights enabled field.
=> MIGENG-507: Insights enabled - new field on WIR - UI implementation

src/Utilities/formatValue.js, src/pages/ReportView/WorkloadInventory/WorkloadInventory.scss, src/pages/ReportView/WorkloadInventory/WorkloadInventory.tsx, src/pages/ReportView/WorkloadInventory/WorkloadInventoryDetails/WorkloadInventoryDetails.tsx, src/pages/ReportView/WorkloadInventory/WorkloadInventoryDetails/__snapshots__/WorkloadInventoryDetails.test.tsx.snap
https://issues.redhat.com/browse/MIGENG-589
Changes required in the ticket.
**Note: The Mockups provided won't 100% match with the implementation. A complete description of the agreements between the UX team and our team has been added to the JIRA ticket.**
=> MIGENG-589: UI implementation - WIR Flags and Targets

profiles/local-frontend-and-api.js, src/api/apiInit.tsx
Adding the base path versioning
https://issues.redhat.com/browse/MIGENG-607
Do it together with : https://github.com/project-xavier/xavier-integration/pull/107
=> Migeng 607 api versioning

profiles/local-frontend-and-api.js, src/PresentationalComponents/EmptyCard/EmptyCard.test.tsx, src/PresentationalComponents/EmptyCard/EmptyCard.tsx, src/PresentationalComponents/EmptyCard/__snapshots__/EmptyCard.test.tsx.snap, src/PresentationalComponents/EmptyCard/index.tsx, src/PresentationalComponents/FancyChartDonut/FancyChartDonut.tsx, src/PresentationalComponents/FancyChartDonut/__snapshots__/FancyChartDonut.test.tsx.snap, src/PresentationalComponents/SolidCard/SolidCard.test.tsx, src/PresentationalComponents/SolidCard/SolidCard.tsx, src/PresentationalComponents/SolidCard/__snapshots__/SolidCard.test.tsx.snap, src/PresentationalComponents/WorkladSummary/ApplicationPlatformsCard/ApplicationPlatformsCard.test.tsx, src/PresentationalComponents/WorkladSummary/ApplicationPlatformsCard/ApplicationPlatformsCard.tsx, src/PresentationalComponents/WorkladSummary/ApplicationPlatformsCard/__snapshots__/ApplicationPlatformsCard.test.tsx.snap, src/PresentationalComponents/WorkladSummary/ApplicationPlatformsCard/index.tsx, src/PresentationalComponents/WorkladSummary/JavaRuntimesCard/JavaRuntimesCard.test.tsx, src/PresentationalComponents/WorkladSummary/JavaRuntimesCard/JavaRuntimesCard.tsx, src/PresentationalComponents/WorkladSummary/JavaRuntimesCard/__snapshots__/JavaRuntimesCard.test.tsx.snap, src/PresentationalComponents/WorkladSummary/JavaRuntimesCard/index.tsx, src/PresentationalComponents/WorkladSummary/OSInformation/OSInformation.test.tsx, src/PresentationalComponents/WorkladSummary/OSInformation/OSInformation.tsx, src/PresentationalComponents/WorkladSummary/OSInformation/__snapshots__/OSInformation.test.tsx.snap, src/PresentationalComponents/WorkladSummary/OSInformation/index.tsx, src/models/Report.tsx, src/pages/ReportView/InitialSavingsEstimation/InitialSavingsEstimation.tsx, src/pages/ReportView/WorkloadSummary/WorkloadSummary.test.tsx, src/pages/ReportView/WorkloadSummary/WorkloadSummary.tsx, src/pages/ReportView/WorkloadSummary/__snapshots__/WorkloadSummary.test.tsx.snap
Changes to the Workload Migration Summary
- https://issues.redhat.com/browse/MIGENG-533
- https://issues.redhat.com/browse/MIGENG-534
- https://issues.redhat.com/browse/MIGENG-535
This PR depends on: https://github.com/project-xavier/xavier-integration/pull/105
Included 3 new panels:
- OS Information
- Oracle Java Runtime Information
- Application Platform Information
=> MIGENG-533 MIGENG-534 MIGENG-535: WSM - OSInformation, JavaRuntimes, and ApplicationPlatforms

src/PresentationalComponents/WorkladSummary/OSInformation/OSInformation.tsx, src/PresentationalComponents/WorkladSummary/OSInformation/__snapshots__/OSInformation.test.tsx.snap
https://issues.redhat.com/browse/MIGENG-533
change from "OS Information" to "OS information"
=> MIGENG-533: WMS "OS Information and recommendations" - Fix title

src/SmartComponents/Reports/FlagsTable/FlagsTable.tsx, src/SmartComponents/Reports/WorkloadsDetectedTable/WorkloadsDetectedTable.tsx, src/api/report.tsx, src/models/Report.tsx, src/reducers/ReportsReducer.tsx
https://issues.redhat.com/browse/MIGENG-624
Depends on: https://github.com/project-xavier/xavier-integration/pull/110
=> MIGENG-624: Pagination - Workload Inventory Report

src/reducers/MappingsReducer.tsx, src/reducers/ReportsReducer.tsx
https://issues.redhat.com/browse/MIGENG-625
Depends on https://github.com/project-xavier/xavier-integration/pull/114
Changed reducers to take correct new fields after pagination API changes is introduced
=> MIGENG-625: API changes Workload Summary Report - pagination

src/api/report.tsx, src/reducers/ReportsReducer.test.tsx, src/reducers/ReportsReducer.tsx
https://issues.redhat.com/browse/MIGENG-622
=> MIGENG-622 changed pagination params for getAllReports

src/SmartComponents/Reports/FlagsTable/FlagsTable.tsx, src/SmartComponents/Reports/WorkloadsDetectedTable/WorkloadsDetectedTable.tsx, src/pages/ReportView/WorkloadInventory/WorkloadInventory.tsx, src/pages/Reports/Reports.tsx
https://issues.redhat.com/browse/MIGENG-641
- Reset page to the first page whenever the user changes `PageSize`
- Removed unneeded imports
=> MIGENG-641: Pagination wrong offset

src/PresentationalComponents/ReportViewPage/ReportViewPage.tsx, src/PresentationalComponents/ReportViewPage/__snapshots__/ReportViewPage.test.tsx.snap, src/PresentationalComponents/Reports/RenewalEstimation/RenewalEstimation.tsx, src/PresentationalComponents/Reports/RenewalEstimation/__snapshots__/RenewalEstimation.test.tsx.snap, src/pages/ReportView/InitialSavingsEstimation/InitialSavingsEstimation.tsx
Changes to address comments in https://issues.redhat.com/browse/MIGENG-654?focusedCommentId=14299158
=> MIGENG-654: typos fixed

src/App.js
ping @carlosthe19916 @m-brophy @PhilipCattanach
=> Remove deprecated function chrome navigation
